had to disable master_ipv4_cidr_block = var.cidr_master_range
because there were an error asking for provider replacement

Error: Provider produced invalid plan

Provider "registry.terraform.io/hashicorp/google-beta" has indicated "requires
replacement" on module.cluster.google_container_cluster.primary for a
non-existent attribute path
cty.Path{cty.GetAttrStep{Name:"private_cluster_config"},
cty.IndexStep{Key:cty.NumberIntVal(0)},
cty.GetAttrStep{Name:"master_ipv4_cidr_block"}}.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

the Issue is unsolved
https://github.com/kbst/terraform-kubestack/pull/132